"""Generate reviewable recovery artefact drafts from a continuity drill.

The generator is deliberately side-effect free until :func:`write_recovery_artifacts`
is called.  That function writes only below the caller-selected output directory;
it never edits a repository, creates GitHub issues, or changes CODEOWNERS.
"""

from __future__ import annotations

import json
import os
import re
import stat
import tempfile
from pathlib import Path
from typing import Iterable

from .models import DrillResult, Finding, RepoSnapshot


def _safe_text(value: object) -> str:
    """Keep generated text one-line and free of control characters."""
    text = str(value).replace("\r", " ").replace("\n", " ")
    text = "".join(char if char.isprintable() or char in "\t" else " � " for char in text).strip()
    # Finding details can originate in repository-controlled metadata.  Avoid
    # carrying obvious inline credentials into a shareable draft.
    return re.sub(
        r"(?i)\b(token|secret|password|passwd|api[_-]?key|authorization)\s*[:=]\s*[^\s,;}]+",
        lambda match: f"{match.group(1)}=[REDACTED]",
        text,
    )


def _markdown_text(value: object) -> str:
    """Render repository-controlled text without Markdown structure injection."""
    text = _safe_text(value).replace("\\", "\\\\")
    punctuation = chr(96) + "*_[\\]()<>{}#+!~|"
    return "".join("\\" + char if char in punctuation else char for char in text)


def _finding_id(scenario: str, finding: Finding) -> str:
    """Return a stable ID even for findings from third-party scenarios."""
    if finding.finding_id:
        return _safe_text(finding.finding_id)
    slug = re.sub(r"[^a-z0-9]+", "-", _safe_text(finding.title).lower()).strip("-") or "finding"
    return f"{_safe_text(scenario)}.{slug}"


def _iter_findings(results: Iterable[DrillResult]):
    for result in results:
        for finding in result.findings:
            yield result, finding, _finding_id(result.scenario, finding)


def render_runbook(repo: RepoSnapshot, results: list[DrillResult]) -> str:
    """Render a human-reviewable incident recovery runbook draft."""
    lines = [
        f"# Continuity recovery runbook draft: {_markdown_text(repo.name)}",
        "",
        "> Draft generated by Maintainer-Zero. Review and adapt before use.",
        "> This file is not an authorization, does not contain credentials, and does not",
        "> automatically change repository settings or create external tickets.",
        "",
        "## Before an incident",
        "",
        "- Assign at least one backup owner for review, merge, build, and release.",
        "- Verify a clean checkout, test command, build command, and release command.",
        "- Store credentials in the platform secret manager; never copy them into this runbook.",
        "- Rehearse this checklist with a disposable branch and record the date.",
        "",
        "## Incident checklist",
        "",
    ]
    finding_count = 0
    for result, finding, identifier in _iter_findings(results):
        finding_count += 1
        lines.extend(
            [
                f"### [{_markdown_text(finding.severity).upper()}] {_markdown_text(result.scenario)}: {_markdown_text(finding.title)}",
                "",
                f"- Finding ID: `{_markdown_text(identifier)}`",
                f"- Evidence: {_markdown_text(finding.detail)}",
                f"- First action: {_markdown_text(finding.action)}",
                "- [ ] Name the incident lead and backup in the incident channel.",
                "- [ ] Record the decision, owner, and verification evidence.",
                "- [ ] Re-run the affected drill after the change.",
                "",
            ]
        )
    if not finding_count:
        lines.extend(["No actionable findings were produced for the selected drills.", ""])
    lines.extend(["## Simulated queue indicators", "", "> These are deterministic model outputs, not observed recovery or service guarantees.", ""])
    for result in results:
        metrics = result.metrics
        if "simulated_peak_backlog" not in metrics:
            continue
        lines.extend(
            [
                f"### {_markdown_text(result.scenario)}",
                "",
                f"- Incident peak backlog: {_safe_text(metrics.get('simulated_peak_backlog'))}",
                f"- Incident ending backlog: {_safe_text(metrics.get('simulated_ending_backlog'))}",
                f"- Simulated service level: {_safe_text(metrics.get('simulated_service_level'))}",
                f"- First simulated recovery day: {_safe_text(metrics.get('simulated_recovery_day'))}",
                f"- Recovery-window ending backlog: {_safe_text(metrics.get('simulated_recovery_ending_backlog'))}",
                f"- Assumed recovery window: {_safe_text(metrics.get('simulated_recovery_window_days'))} days",
                "",
            ]
        )
    lines.extend(
        [
            "## Recovery verification",
            "",
            "- [ ] A second person can review and merge a small change.",
            "- [ ] A clean environment can install dependencies without a private cache.",
            "- [ ] CI fallback or manual test evidence is attached to the release decision.",
            "- [ ] The release can be rebuilt and verified without the unavailable operator.",
            "- [ ] Follow-up owners and due dates are tracked in the project issue tracker.",
            "",
            "## Drill assumptions",
            "",
        ]
    )
    assumptions = [assumption for result in results for assumption in result.assumptions]
    lines.extend(f"- {_markdown_text(assumption)}" for assumption in assumptions)
    if not assumptions:
        lines.append("- No assumptions were recorded; treat missing evidence as unknown.")
    return "\n".join(lines) + "\n"


def render_codeowners_draft(repo: RepoSnapshot, results: list[DrillResult]) -> str:
    """Render a placeholder CODEOWNERS proposal without guessing identities."""
    del results  # The draft is intentionally conservative and identity-free.
    lines = [
        "# Maintainer-Zero draft — NOT applied automatically",
        f"# Repository: {_markdown_text(repo.name)}",
        "# Replace placeholders with a team or verified GitHub handles.",
        "# Keep this draft under review; do not commit it without an owner.",
        "",
        "# Critical continuity paths",
        "/.github/ @backup-maintainer",
        "/.github/workflows/ @release-backup",
        "/CODEOWNERS @backup-maintainer",
        "",
        "# Suggested team aliases (replace before committing)",
        "# @backup-maintainer",
        "# @release-backup",
    ]
    return "\n".join(lines) + "\n"


def render_issue_drafts(repo: RepoSnapshot, results: list[DrillResult]) -> str:
    """Render copy/paste issue drafts; no network or external mutation occurs."""
    lines = [
        f"# Continuity issue drafts: {_markdown_text(repo.name)}",
        "",
        "> These are drafts only. Maintainer-Zero never submits them automatically.",
        "",
    ]
    finding_count = 0
    for result, finding, identifier in _iter_findings(results):
        finding_count += 1
        lines.extend(
            [
                f"## [Continuity] {_markdown_text(result.scenario)} — {_markdown_text(finding.title)}",
                "",
                f"**Finding ID:** `{_markdown_text(identifier)}`  ",
                f"**Severity:** `{_markdown_text(finding.severity)}`",
                "",
                "### Why this matters",
                "",
                _markdown_text(finding.detail),
                "",
                "### Proposed recovery",
                "",
                _markdown_text(finding.action),
                "",
                "### Definition of done",
                "",
                "- [ ] An owner and due date are assigned.",
                "- [ ] The recovery path is tested from a clean environment.",
                "- [ ] The corresponding drill is rerun and the result is attached.",
                "",
                "---",
                "",
            ]
        )
    if not finding_count:
        lines.extend(["No issue drafts: no actionable findings were produced.", ""])
    return "\n".join(lines)


def render_sarif(repo: RepoSnapshot, results: list[DrillResult]) -> str:
    """Render findings as SARIF 2.1.0 for GitHub Code Scanning ingestion.

    Findings are repository-level observations, so this intentionally omits a
    source location rather than inventing a file/line.  The payload contains
    only sanitized finding text and can be reviewed before upload.
    """
    rules: dict[str, dict[str, object]] = {}
    sarif_results: list[dict[str, object]] = []
    level_map = {"high": "error", "medium": "warning", "low": "note"}
    for result, finding, identifier in _iter_findings(results):
        severity = _safe_text(finding.severity).lower()
        rules.setdefault(
            identifier,
            {
                "id": identifier,
                "name": identifier,
                "shortDescription": {"text": _safe_text(finding.title)},
                "help": {"text": _safe_text(finding.action)},
                "properties": {"security-severity": {"high": "8.0", "medium": "5.0", "low": "2.0"}.get(severity, "1.0")},
            },
        )
        sarif_results.append(
            {
                "ruleId": identifier,
                "level": level_map.get(severity, "warning"),
                "message": {"text": f"{_safe_text(finding.detail)} Action: {_safe_text(finding.action)}"},
                "properties": {"scenario": _safe_text(result.scenario), "score": result.score},
            }
        )
    payload = {
        "$schema": "https://json.schemastore.org/sarif-2.1.0.json",
        "version": "2.1.0",
        "runs": [
            {
                "tool": {"driver": {"name": "Maintainer-Zero", "version": "0.2", "informationUri": "https://github.com/"}},
                "automationDetails": {"id": f"maintainer-zero/{_safe_text(repo.name)}"},
                "results": sarif_results,
                "rules": list(rules.values()),
            }
        ],
    }
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"

def _atomic_write_text(path: str | Path, content: str) -> None:
    """Atomically replace one recovery draft in its output directory."""
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    temporary: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(mode="w", encoding="utf-8", newline="", dir=target.parent, prefix=f".{target.name}.", suffix=".tmp", delete=False) as handle:
            temporary = Path(handle.name)
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, target)
        temporary = None
    finally:
        if temporary is not None:
            temporary.unlink(missing_ok=True)


def _safe_output_directory(path: str | Path) -> Path:
    """Create and validate an output directory without following links.

    Recovery artifacts are often uploaded or copied outside the repository.
    Rejecting symlinked path components keeps an attacker-controlled output
    path from redirecting those writes into an unrelated directory.
    """
    target = Path(path)
    if not target.is_absolute():
        target = Path.cwd() / target
    current = Path(target.anchor) if target.anchor else Path()
    parts = target.parts[1:] if target.anchor else target.parts
    for part in parts:
        current /= part
        try:
            info = current.lstat()
        except FileNotFoundError:
            try:
                current.mkdir()
                info = current.lstat()
            except OSError as exc:
                raise ValueError(f"could not create recovery output directory: {current}") from exc
        except OSError as exc:
            raise ValueError(f"could not inspect recovery output directory: {current}") from exc
        if stat.S_ISLNK(info.st_mode):
            raise ValueError(f"recovery output path may not contain a symlink: {current}")
        if not stat.S_ISDIR(info.st_mode):
            raise ValueError(f"recovery output path is not a directory: {current}")
    return target


def _artifact_backup_path(directory: Path, filename: str) -> Path:
    """Reserve a unique same-directory path for one rollback backup."""
    handle = tempfile.NamedTemporaryFile(
        mode="wb", dir=directory, prefix=f".{filename}.", suffix=".bak", delete=False
    )
    path = Path(handle.name)
    handle.close()
    path.unlink(missing_ok=True)
    return path


def _atomic_write_artifacts(out: Path, artefacts: dict[str, str]) -> list[Path]:
    """Replace all recovery artifacts as one rollback-capable generation."""
    staged: dict[Path, Path] = {}
    backups: dict[Path, Path] = {}
    replaced: list[Path] = []
    try:
        for filename, content in artefacts.items():
            target = out / filename
            with tempfile.NamedTemporaryFile(
                mode="w", encoding="utf-8", newline="", dir=out,
                prefix=f".{target.name}.", suffix=".tmp", delete=False
            ) as handle:
                staged[target] = Path(handle.name)
                handle.write(content)
                handle.flush()
                os.fsync(handle.fileno())

        for target, temporary in list(staged.items()):
            if os.path.lexists(target):
                backup = _artifact_backup_path(out, target.name)
                os.replace(target, backup)
                backups[target] = backup
            os.replace(temporary, target)
            replaced.append(target)
            staged.pop(target, None)
        return [out / filename for filename in artefacts]
    except BaseException:
        for target in reversed(replaced):
            try:
                target.unlink(missing_ok=True)
            except OSError:
                pass
        for target, backup in backups.items():
            if backup.exists() or os.path.lexists(backup):
                try:
                    # Rollback intentionally uses rename rather than the
                    # replace hook used for the forward commit.  This keeps
                    # an injected replacement failure from also preventing
                    # restoration of the previous generation.
                    os.rename(backup, target)
                except OSError:
                    pass
        raise
    finally:
        for temporary in staged.values():
            temporary.unlink(missing_ok=True)
        for backup in backups.values():
            backup.unlink(missing_ok=True)


def write_recovery_artifacts(out: Path, repo: RepoSnapshot, results: list[DrillResult]) -> list[Path]:
    """Write recovery drafts below *out* and return paths in stable order."""
    out = _safe_output_directory(out)
    artefacts = {
        "runbook.md": render_runbook(repo, results),
        "CODEOWNERS.draft": render_codeowners_draft(repo, results),
        "issue-drafts.md": render_issue_drafts(repo, results),
        "continuity.sarif": render_sarif(repo, results),
    }
    return _atomic_write_artifacts(out, artefacts)
